### ISSUE TITLE
Extension error 

### ISSUE THREAD

**Issue by dot-ly** [MobileEssentials/FormsPlayer#5]
i'm getting the following error when i try to run the Forms Player extension on VS studio  

 <entry>
    <record>889</record>
    <time>2015/10/14 17:09:40.103</time>
    <type>Information</type>
    <source>VSGallery0f45e40879954375948586b8db553dc9</source>
    <description>Extension &apos;Xamarin.Forms.Player&apos; has a current version of &apos;0.1.8&apos; that is less than the installed version &apos;0.1.8&apos;</description>
  </entry>
  <entry>
    <record>890</record>
    <time>2015/10/14 17:09:40.103</time>
    <type>Information</type>
    <source>VSGallery0f45e40879954375948586b8db553dc9</source>
    <description>Extension &apos;Microsoft.WinJS&apos; has a current version of &apos;&apos; that is less than the installed version &apos;1.0.9651.40228&apos;</description>
  </entry>

**Comment by kzu** [comment]
Looks like you have it installed already? Uninstall your current one and reinstall the gallery one?

**Comment by dot-ly** [comment]
FYI , i got this working by running it on VS2015. It Would not work on VS2013 for some reason.... uninstalled and installed again a few times but no luck!
